# Generated by Django 2.1.1 on 2018-09-24 21:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, verbose_name='Target url')),
                ('file_path', models.FilePathField(blank=True, db_index=True, null=True, verbose_name='File path')),
                ('duration', models.DurationField(default=datetime.timedelta(0), max_length=255, verbose_name='Duration')),
                ('progress', models.IntegerField(default=0, verbose_name='Progress')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Init time')),
                ('auto_pause', models.BooleanField(default=False, verbose_name='Set pause automatically')),
                ('auto_pause_time', models.DateTimeField(null=True, verbose_name='Pause download at this time')),
                ('auto_resume_time', models.DateTimeField(null=True, verbose_name='Resume download at this time')),
                ('status', models.IntegerField(choices=[(0, 'Started'), (1, 'Paused'), (2, 'Canceled'), (3, 'Deleted'), (4, 'Completed'), (5, 'On hold')], default=5, verbose_name='Status')),
                ('priority', models.IntegerField(choices=[(1, 'High priority'), (2, 'Medium priority'), (3, 'Low priority')], default=2, verbose_name='Priority')),
                ('scope', models.IntegerField(choices=[(1, 'Private'), (2, 'Public')], default=2, verbose_name='Scope')),
            ],
        ),
        migrations.CreateModel(
            name='FileMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Size of the file')),
                ('type', models.CharField(max_length=255, verbose_name='File type')),
            ],
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='file_metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.FileMetaData'),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
