# Generated by Django 2.1.1 on 2018-09-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtask',
            name='auto_pause_time',
            field=models.TimeField(null=True, verbose_name='Pause download at this time'),
        ),
        migrations.AlterField(
            model_name='downloadtask',
            name='auto_resume_time',
            field=models.TimeField(null=True, verbose_name='Resume download at this time'),
        ),
    ]
