# Generated by Django 2.1.1 on 2018-10-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20180924_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtask',
            name='auto_pause_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Pause download at this time'),
        ),
        migrations.AlterField(
            model_name='downloadtask',
            name='auto_resume_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Resume download at this time'),
        ),
    ]
